# Generated by Django 3.1.7 on 2021-04-06 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stroka',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='stroka',
            name='title',
            field=models.CharField(max_length=10, verbose_name='Название'),
        ),
    ]
