# Generated by Django 3.1.7 on 2021-04-13 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_auto_20210409_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stroka',
            name='create_at',
            field=models.DateTimeField(verbose_name='auto_add_now = True'),
        ),
    ]
